name:                hoggle
version:             0.1.0.0
github:              "samcoy3/hoggle"
license:             BSD3
author:              "Sam Coy"
maintainer:          "samjtcoy@gmail.com"
copyright:           "2020 Sam Coy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A Boggle web-app, written in Haskell.

dependencies:
- aeson
- base >= 4.7 && < 5
- containers >= 0.6
- http-api-data
- primitive >= 0.7
- random >= 1.1
- text >= 0.11
- time >= 1.9
- transformers >= 0.5
- servant == 0.18.2
- servant-server >= 0.18
- stm >= 2.5
- uuid >= 1.3
- wai >= 3.2
- warp

library:
  source-dirs: src

executables:
  hoggle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoggle
